#######################################################################
#
# General Options
#

## Operation System 
OS = LINUX
#OS = SOLARIS
#OS = QNX
#OS = FREEBSD
#OS = AIX
#OS = IRIX
#OS = WIN32

## MPI library
MPI_LIBRARY = NULLMPI
#MPI_LIBRARY = MPICH2
#MPI_LIBRARY = OPENMPI
#MPI_LIBRARY = MPIPRO
#MPI_LIBRARY = DEINOMPI

## UthLib
#UTHLIB = UTH_PTH
ifeq ($(UTHLIB), UTH_PTH)
UTHLIBDIR = $(BASEDIR)/uth_pth
else
UTHLIBDIR = $(BASEDIR)/uth
endif


## Default Compiler (GCC) and Options
#CC = mpicc
#F77 = mpif77 
CC = gcc
F77 = g77

COPTS = -Wall -g -ggdb # -m32 # -O3
FOPTS = -fugly-logint # -fno-second-underscore # -m32

#######################################################################
#
# Platform (OS) Specific Options
#

#######################################################################
#
# MPI Library
#

ifeq ($(MPI_LIBRARY), NULLMPI) 
MPI_INSTALLDIR = $(BASEDIR)/nullmpi
MPI_LIB = 
MPI_INCDIR = -I$(BASEDIR)/nullmpi/include
endif


#######################################################################
#
# LWRPC Library
#

LWRPC_FLAGS = 

LWRPC_FLAGS += -DLWRPC_STATS
#LWRPC_FLAGS += -DREGISTER_INTERNODE_FUNCTIONS
#LWRPC_FLAGS += -DBLOCK_IDLE_THREADS
#LWRPC_FLAGS += -DNONBLOCKING

#######################################################################
#
# Compilation Options and Rules
#

DEFINES = -D_REENTRANT -D_THREAD_SAFE -D_XOPEN_SOURCE=600 # -DDBG=1
CCOPTS = $(COPTS) -D$(OS) $(LWRPC_FLAGS)
FCOPTS = $(FOPTS) -D$(OS) $(LWRPC_FLAGS)

INCDIR = -I${BASEDIR}/include -I${UTHLIBDIR}
LIBDIR = -L${BASEDIR}/src -L${UTHLIBDIR}

LIBS = -llwrpc -luth -lpthread -lm
NTHMAINCLIB = -llwrpc_main
NTHMAINFLIB = -llwrpc_fmain
SLIBS = ${BASEDIR}/src/liblwrpc.a ${UTHLIBDIR}/libuth.a 

CFLAGS = $(CCOPTS) $(DEFINES) $(INCDIR) $(MPI_INCDIR)
FFLAGS = $(FCOPTS) $(DEFINES) $(INCDIR) $(MPI_INCDIR)
LDFLAGS = $(LIBDIR) $(LIBS) # -m32
MAINLDFLAGS = $(LIBDIR) $(NTHMAINCLIB) $(LIBS)

.f.o:
	$(F77) $(FFLAGS) -c $<

.c.o:
	$(CC) $(CFLAGS) -c $<

AR = ar
RM = rm -f 
#RM = del

################################################################################
#
#
#


